version: '3.8'

volumes:
  db:
    driver: local

services:
  mariadb5:
    container_name: mariadb5_livraria
    image: mariadb:5.5.64
    restart: always
    volumes:
        - ./lib:/var/lib/mysql
        - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3310:3306"
  mariadb10:
    container_name: mariadb10_livraria
    image: mariadb:10.11.5
    restart: always
    volumes:
      - ./lib2:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3309:3306"